### ISSUE TITLE
Portuguese log

### ISSUE THREAD

**Issue by edysegura** [auromota/shopping-cart#2]
Is there a reason to keep this log in portuguese?

![image](https://cloud.githubusercontent.com/assets/5324414/16358731/ace24eb2-3af2-11e6-91aa-f02e65d1be6c.png)

**Comment by auromota** [comment]
Hey, @edysegura!

I forgot to remove them. I rewrote some parts of the application and have just merged my development branch to the master branch. The log is not there anymore. :+1: 

Thanks!
